fix: don't reset index to 0 on file deletion
ArturKovacs/emulsion pull request #156
Opened 2020-11-12 09:09 UTC by ahkrr

The behavior before this PR was, that the index would be set to 0 on 
every file deletion.

This probably isn't the desired behavior. 
Now, the program first checks for the file-name, than the index and only after that setting the index to 0.

2020-11-12 21:04 UTC, ArturKovacs requested changes
Hey, thanks opening a PR! 😊

Yes, this should indeed behave the way you intended however there are just a couple of things I'd like you to resolve before I merge this.

2020-11-12 21:04 UTC, ArturKovacs commented on src/image_cache/directory.rs
> +		// if possible preserve previous file_name
I'm guessing you meant to put this right before the next loop as it is out of place here.

2020-11-12 21:04 UTC, ArturKovacs commented on src/image_cache/directory.rs
> +			if is_file_supported(&PathBuf::from(desc.path.file_name().unwrap())) {
This should be
```rust
if is_file_supported(&desc.path) {
```

2020-11-12 21:37 UTC, ahkrr commented
The changes are done.

2020-11-13 07:25 UTC, ArturKovacs approved these changes
Thank you! I'm such a dummy by the way. I just realized that the comment in fact referred to the first loop. I'm embarassed. Anyhow I don't want to waste any more of your time so I'll accept this as it is.

2020-11-13 07:27 UTC, merged