Enhance: set dark mode in config
ArturKovacs/emulsion pull request #206
Opened 2021-08-25 22:48 UTC by carrascomj

### Description
As a user, I'd like to set dark mode in the configuration file, mainly because that is something a user may expect to set there (and I have the bar hidden so I can't just rely on the cache for fresh installs with my config files).

This PR simply adds a field theme at the root of the `cfg.toml` file:

```toml
theme="Dark"

[bindings]
# everything remains the same
```

### Implementation
A field `theme` was added to [`Configuration`](https://github.com/ArturKovacs/emulsion/blob/master/src/configuration.rs#L226), in the same fashion than `Cache`. Points to consider:

* This configuration field takes precedence over cache's as in the `window` field, is that fine?
* `Serialize` and `Deserialize` were derived for `Theme`, what do you think of [`#[serde(rename_all = "lowercase")]`](https://serde.rs/container-attrs.html#rename_all) so that it becomes the following at `cfg.toml`:
```toml
theme="dark"
```
* The default stays the same (Light).
* Maybe `theme` should be a field of [`ConfigWindowSection`](https://github.com/ArturKovacs/emulsion/blob/master/src/configuration.rs#L73) (?), whatever is cleaner.

2021-09-03 06:04 UTC, ArturKovacs commented
Thanks for the PR!

I lost motivation to keep working on Emulsion a while ago. It definitely feels good to see that there's someone who cares this much about it. I will review this PR this weekend, and probably I'll make a new release with these changes.

Note to self: update `arboard` before the release.

2021-09-04 07:12 UTC, ArturKovacs commented
This is a great idea, and I agree with you that the `theme` should be a field of [`ConfigWindowSection`](https://github.com/ArturKovacs/emulsion/blob/master/src/configuration.rs#L73).

I also like your serde rename suggestion but we should use `#[serde(rename_all = "snake_case")]` instead of `lowercase`. And please do the same with the `Antialias` enum while you are at it. Thanks!

One more thing: please add a sentence about this to the `CHANGELOG.md`, in the "Added" section (you might have to create it).

2021-09-06 18:07 UTC, carrascomj commented
That's it, although I have no idea why it is passing the tests now (I did not fix the clippy errors).

It is sad to hear you lost your motivation on emulsion, but I can totally understand the toll of being an open-source maintainer. The good thing is that it is easy to call emulsion feature-complete (apart from the proper SVG rendering on zoom :sweat_smile:), so the users will stay happy with it in the foreseeable future.

2021-09-13 19:00 UTC, ArturKovacs requested changes
There are two more small things, and this should be ready to merge.

2021-09-13 19:00 UTC, ArturKovacs commented on src/configuration.rs
>  	#[serde(rename = "auto")]
I believe you can remove the `#[serde(rename = "...")]` from this enum because now we have the `rename_all`.

2021-09-13 19:01 UTC, ArturKovacs commented
> That's it, although I have no idea why it is passing the tests now (I did not fix the clippy errors).

Because I fixed them on master.

> The good thing is that it is easy to call emulsion feature-complete (apart from the proper SVG rendering on zoom 😅), so the users will stay happy with it in the foreseeable future.

Thanks for the kind words! 😊 I tend to see its errors more often than its features. So yeah the incorrect SVG rendering is precisely one of the things that annoy me a great deal. Not that I view so many SVG files it's just the thought that it's incomplete.

2021-09-13 19:50 UTC, carrascomj commented on CHANGELOG.md
> +- Change antialias configuration keywords to snake_case.
Uh, right, sorry. I did not even notice that `Antialias` had all of these renames in the first place.

2021-09-16 16:35 UTC, merged